### ISSUE TITLE
Failed to open device

### ISSUE THREAD

**Issue by h1t2y3g4** [wuxx/nanoDLA#10]
当我按照readme的教程安装完成驱动后，打开pulseview，弹窗提醒我无法打开设备。
进入到软件的日志，报错信息如下：
fx2lafw: Failed to open potential device with VID:PID 1d50:608c: LIBUSB_ERROR_NOT_SUPPORTED.
fx2lafw: Failed to open device: LIBUSB_ERROR_NOT_SUPPORTED.
sr: fx2lafw: Unable to open device.
Notifying user of session error: "generic/unspecified error"

奇怪的是，同样的逻辑分析仪，同样的安装操作步骤，同样用的win10。在我的旧电脑上是可以正常使用的，但是现在在我的新电脑上安装后就出问题了，我的新电脑CPU是5800x。不知道是AMD平台的问题还是我缺少什么文件？

**Comment by wuxx** [comment]
换个USB接口插试试看，这个是USB 2.0 高速的设备，带宽480Mbps

**Comment by h1t2y3g4** [comment]
哇真的耶，我的机箱前面板有两个usb2.0的接口，他们都是从主板上同一个usb2.0接口分出来的。
这两个接口中有一个我插了个1000hz回报率的鼠标，另一个接口插逻辑分析仪就不行，当我换到usb3.0上时就可以了。
之前的电脑我都是插在usb2.0上用的，同样也是集线器，但是集线器上所有设备都是正常的，所以就没有怀疑这个问题。现在想想可能是当时设备用的带宽低，所以没问题。鸟枪换炮出问题的属于是。
