### ISSUE TITLE
可以给逻辑分析仪整合数据反写功能，将上位机分析好的数据直接通过测试数据线，写到下位机

### ISSUE THREAD

**Issue by gitQqqHs** [wuxx/nanoDLA#12]
调板子的时候突然发现的一个需求。
逻辑分析仪在接收到数据后，进行分析，可以对上一级芯片输出的数据进行验证。同时还可以进行协议的相位和极性进行调整。
即使上一级输出的数据和pin脚配置是正确的，但是在连接到下一级芯片后，系统无法正常工作。
同时下一级芯片功能也是正常的。
如果逻辑分析仪有数据反写共呢个，则可以通过逻辑分析仪对下一级芯片进行数据传输，快速验证下一级芯片的功能完整性。不需要单独使用其他工具进行数据通信的验证。
比如我使用stm32系统对锁相环进行配置，spi通信，一切正常
但是转到fpga后，通信不正常。但是fpga连接到逻辑分析仪，输出的数据是正确的。
这个时候，如果逻辑分析仪有数据反写功能，在验证了fpga的数据输出后，可以通过已经分析的数据，使用逻辑分析仪写到锁相环，而不是使用其他工具，这样节省了很多时间。
确定了故障的位置，可以分开调试。

**Comment by wuxx** [comment]
指的是逻辑分析仪内存储好信号时序，然后回放吗
