### ISSUE TITLE
linux(ubuntu) Which software should be used ?

### ISSUE THREAD

**Issue by hyzgit** [wuxx/nanoDLA#16]
I don't think I can find the corresponding version

**Comment by elfmimi** [comment]
**PulseView** is what you need.

Debian link
https://packages.debian.org/stable/electronics/pulseview

Ubuntu link
https://packages.ubuntu.com/focal/pulseview

PulseView manual link
https://www.sigrok.org/doc/pulseview/0.4.2/manual.html
