### ISSUE TITLE
NanoDLA输入端口状态问题

### ISSUE THREAD

**Issue by FreeHans** [wuxx/nanoDLA#17]
1. NanoDLA的8个输入通道的IO是否能设置为高阻状态，买过来测试时发现，被测板断电后，输入IO会向被测板子供电，影响测试（由于被测板子无法断电，所以无法抓取被测板子上电时的信号），如果可以设置麻烦更新下固件
2. 看到别人提的信号回放比较期待，先抓取信号，再通过NanoDLA输出回放

**Comment by wuxx** [comment]
1. 可以尝试加一个二极管单向导通，或者加一个74缓冲芯片
2. 这个功能确实比较实用，需要时间研究实现，涉及固件/pulseview上位机，目前使用的是开源未修改的源码固件（不过此功能只能适配目前的逻辑分析仪硬件版本，因为一般采样信号线上有74缓冲芯片，信号是单向流动的）
