### ISSUE TITLE
i2c解析错误

### ISSUE THREAD

**Issue by chonger271** [wuxx/nanoDLA#18]
![image](https://user-images.githubusercontent.com/104484401/165449939-7d690bfd-93d3-4884-91e0-a3c6d8c677f0.png)
i2c解析时，起始信号识别错误，导致后续时序错乱。

**Comment by wuxx** [comment]
尝试提高采样率看看

**Comment by chonger271** [comment]
![image](https://user-images.githubusercontent.com/104484401/165451103-2d1107e9-61fa-4fdf-8dc0-f01daaa35f44.png)
i2c总线是100K的，采样率已经设置到8MHz了，问题仍然存在

**Comment by wuxx** [comment]
另存为sr文件，把完整的波形发上来看看

**Comment by chonger271** [comment]
[20220427chonger.zip](https://github.com/wuxx/nanoDLA/files/8570660/20220427chonger.zip)
谢谢

**Comment by wuxx** [comment]
发现你的波形上面有8MHz的毛刺，不正常，检查接线干扰、杜邦线的长度不要长于30cm
![image](https://user-images.githubusercontent.com/1648489/165486062-ea60e90a-08a3-4799-9f62-c728835f80a4.png)

**Comment by chonger271** [comment]
![image](https://user-images.githubusercontent.com/104484401/165487328-e6f16b41-9ed3-4865-ac83-7e84b8a1d4d6.png)
我明天再找跟线试试。但438830us开始的这段没有毛刺干扰，解析也不正常

**Comment by chonger271** [comment]
换了线还是不行，还是由干扰信号，但是对解析影响不大吧
![image](https://user-images.githubusercontent.com/104484401/165659771-e354e622-4db1-4588-91dc-fcc319a4edc4.png)
只有停止信号和开始信号解析时易出错
![image](https://user-images.githubusercontent.com/104484401/165657788-c6962e0f-6b90-4cba-bfd4-4028d9287dc1.png)
停止信号和起始信号解析错误
![image](https://user-images.githubusercontent.com/104484401/165658868-44c303a6-0bd6-4c85-a9c1-ac6fa0f5ef22.png)
有时又是正常的

**Comment by chonger271** [comment]
每次出现 Sr 信号之后 停止信号和开始信号就会解析错误。没有 Sr 信号时解析就正常。
![image](https://user-images.githubusercontent.com/104484401/165661007-d5a1f0be-1263-4e19-93bb-c71a09534186.png)

**Comment by wuxx** [comment]
这两部分是START STOP信号，是否是软件代码问题？
![image](https://user-images.githubusercontent.com/1648489/165662388-83625cde-b148-4250-b331-191035749541.png)

**Comment by chonger271** [comment]
我也不知道为什么会有这种信号。但另一款逻辑分析仪可以正常解析
![image](https://user-images.githubusercontent.com/104484401/165663917-8264a591-2959-45f0-bc26-3d885888493e.png)
![image](https://user-images.githubusercontent.com/104484401/165664055-2cdab514-369b-4c0f-8ac0-de6732c6e391.png)

**Comment by wuxx** [comment]
这种应该是不符合I2C规范的信号，如果要刨根究底，你可以看看pulseview里解析I2C的协议的python脚本，是基于状态机迁移解析的。
C:\Program Files (x86)\sigrok\PulseView\share\libsigrokdecode\decoders\i2c\pd.py

**Comment by wuxx** [comment]
start状态后会迁移到'FIND ADDRESS'，你的信号却是STOP，所以解析会有问题。
![image](https://user-images.githubusercontent.com/1648489/165665187-93f00b15-e247-4e5c-a145-eb3f00211bfe.png)

**Comment by chonger271** [comment]
好的，明白了，感谢你的帮助，谢谢。
