### ISSUE TITLE
Merge nanoDLA drivers with sigrok main

### ISSUE THREAD

**Issue by Bazmundi** [wuxx/nanoDLA#2]
Having a non-standard version of sigrok pulseview makes no sense if people use it with other devices.   There is no guarantee this version will keep up and it will likely not include evolving devices that the sigrok community support.   The drivers of nanoDLA should be merged into the main sigrok pulseview site at: https://sigrok.org/

**Comment by wuxx** [comment]
hello, the chip is compatible with cypress cy7c68013a, and the firmware is fx2lafw, so we use the standard sigrok software and firmware.

**Comment by Bazmundi** [comment]
Yes but you don't need to separately distribute sigrok binaries as it
confuses because it appears the you have your own orphan pulseview software. Just point to sigrok site and include any special instructions for using your hardware with someone elses software.

**Comment by wuxx** [comment]
ok, but somebody may like everything in a single repo, so put here for convenient, I think add a README under software will better
