### ISSUE TITLE
Failed to launch PulseView (w/ workaround)

### ISSUE THREAD

**Issue by foxhoundsk** [wuxx/nanoDLA#24]
Launching PulseView on Linux (Archlinux) gives this error:
```
pulseview: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

This contradicts the philosophy of AppImage, meaning the executable should be runnable on any Linux environments.

After doing some web search, I found [this workaround](https://forum.manjaro.org/t/cannot-run-an-appimage-libgio-2-0-undefined-symbol-issue/119806/2).

It seems that a lib called `libgmodule` shouldn't be included in the image. Removing the lib and repack the image solves the error above.

@wuxx You can repack the AppImage to solve the issue.

It would be good to know that why you include libgmodule in the image, I'm just be curious about this.

Thanks!

**Comment by wuxx** [comment]
very useful information, and the appimage is direct get from [sigrok.org ](https://sigrok.org/wiki/Downloads)
 It may be better to raise an issue in the bug tracking page of sigrok.org
