### ISSUE TITLE
可以被pulseview识别设备，但无法采样

### ISSUE THREAD

**Issue by zephyrwing** [wuxx/nanoDLA#25]
我在ubuntu中用源码编译的pulseview，运行时可以被软件识别为sigrok FX2 LA (8ch)，但是点击run后并没有反应。从后台看到如下错误提示：

sr: fx2lafw: resubmit_transfer: LIBUSB_ERROR_NO_DEVICE
Acquisition took 0.03 s

**Comment by wuxx** [comment]
换个USB试试看，或者拔掉其他USB设备排查看看，一般就能解决
