### ISSUE TITLE
What are the jumpers on the back of the PCB for?

### ISSUE THREAD

**Issue by RChadwick7** [wuxx/nanoDLA#26]
The two jumpers look like this might change the VID/PID so it would work with Saleae Software. Is this true? Or do these do something else?

**Comment by wuxx** [comment]
hello, it's for control the boot mode of CY7C68013A, C0 or C2, you can check the datasheet for detail.

**Comment by minkione** [comment]
Hi, can you provide the instructions to flash the eeprom with the correct 8CH VID-PID to use it with Pulseview?
Xie Xie!

**Comment by minkione** [comment]
As I understood if A0 is high (3V3) the I2C setting will be 0xC2. Which means it loads the VID-PID from RAM.
![image](https://github.com/wuxx/nanoDLA/assets/25242404/ca3e94c2-438d-4c92-a11e-293f88ab8734)
**It means by default your LA does not rely on the EEPROM?**

![image](https://github.com/wuxx/nanoDLA/assets/25242404/ecaa02c4-5f35-458a-922d-fd39ee700903)

**Comment by wuxx** [comment]
you can check these repos
https://github.com/ribalda/fx2eeprom
https://github.com/esden/fxload

**Comment by wuxx** [comment]
[fxload-full-2008_10_13-ww3.tar.gz](https://github.com/wuxx/nanoDLA/files/15307949/fxload-full-2008_10_13-ww3.tar.gz)

**Comment by wuxx** [comment]
https://github.com/esden/fxload

**Comment by minkione** [comment]
Thanks! 🫡
![image](https://github.com/wuxx/nanoDLA/assets/25242404/ee4decc6-e250-4069-ab5d-b3bc48390484)
Which one I shall use to flash the eeprom to use the FX2LP with pulseview?
And especially what would be the VID:PID and the correct command arguments you used on the nanoDLA?
Something like this?
`./fxload -D /dev/bus/usb/aaa/bbb -I firmware.hex -c 0x01 -s Vend_Ax.hex -t fx2lp`

I have purchased this version below and would like to experiment a bit with different firmwares and try both pulseview and saleae's Logic SW...
![nanoDLA](https://github.com/wuxx/nanoDLA/assets/25242404/f5eac2b1-435f-49a4-bb8d-ce7dcb3352bf)

**Comment by minkione** [comment]
I would extremely grateful if you add to the README the two commands to flash the EEPROM on NanoDLA:
1) To dump the original EEPROM of the NanoDLA (as backup)
2) To turn it into a Saleae Logic 
3) To restore the initial backup dump. To roll-back to the original NanoDLA.
Thanks a lot! :)

**Comment by minkione** [comment]
Any suggestion is very appreciated.
I would like to experiment with different FWs... but I prefer to be sure of the right commands and arguments.... before bricking the NanoDLA 😅

**Comment by wuxx** [comment]
You can flash other firmware at will, this will not damage nanoDLA

**Comment by minkione** [comment]
ok, but what is the right command?
Something like this?
`./fxload -D /dev/bus/usb/aaa/bbb -I firmware.hex -c 0x01 -s Vend_Ax.hex -t fx2lp`

**Comment by wuxx** [comment]
here is an example run on Linux
./fxload -I /home/pi/oss/sigrok-firmware-fx2lafw/hw/sigrok-fx2-8ch/fx2lafw-sigrok-fx2-8ch.ihx -D /dev/bus/usb/001/015 -c 0x1 -s ./Vend_Ax.hex -t fx2lp -v

**Comment by minkione** [comment]
Thanks! Will have it a try!

**Comment by RChadwick7** [comment]
Hey @minkione did you ever manage to flash the VID/PID?
