### ISSUE TITLE
请问有没有32位的windows上位机软件

### ISSUE THREAD

**Issue by xuanmumy** [wuxx/nanoDLA#27]
如题

**Comment by yichang99** [comment]
https://github.com/sigrokproject/pulseview/releases/download/continuous/pulseview-NIGHTLY-x86_64-release-installer.exe发自我的手机-------- 原始邮件 --------发件人： mklinux ***@***.***>日期： 2024年11月20日周三 23:03收件人： wuxx/nanoDLA ***@***.***>抄送： Subscribed ***@***.***>主    题： [wuxx/nanoDLA] 请问有没有32位的windows上位机软件 (Issue #27)
如题

**Comment by wuxx** [comment]
可以在sigrok.org 上下载32位的
